// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"github.com/kong/pg-aurora-client/internal/store/ent/aurorahealthcheck"
	"github.com/kong/pg-aurora-client/internal/store/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeAuroraHealthCheck = "AuroraHealthCheck"
)

// AuroraHealthCheckMutation represents an operation that mutates the AuroraHealthCheck nodes in the graph.
type AuroraHealthCheckMutation struct {
	config
	op            Op
	typ           string
	id            *int
	ts            *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*AuroraHealthCheck, error)
	predicates    []predicate.AuroraHealthCheck
}

var _ ent.Mutation = (*AuroraHealthCheckMutation)(nil)

// aurorahealthcheckOption allows management of the mutation configuration using functional options.
type aurorahealthcheckOption func(*AuroraHealthCheckMutation)

// newAuroraHealthCheckMutation creates new mutation for the AuroraHealthCheck entity.
func newAuroraHealthCheckMutation(c config, op Op, opts ...aurorahealthcheckOption) *AuroraHealthCheckMutation {
	m := &AuroraHealthCheckMutation{
		config:        c,
		op:            op,
		typ:           TypeAuroraHealthCheck,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAuroraHealthCheckID sets the ID field of the mutation.
func withAuroraHealthCheckID(id int) aurorahealthcheckOption {
	return func(m *AuroraHealthCheckMutation) {
		var (
			err   error
			once  sync.Once
			value *AuroraHealthCheck
		)
		m.oldValue = func(ctx context.Context) (*AuroraHealthCheck, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().AuroraHealthCheck.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAuroraHealthCheck sets the old AuroraHealthCheck of the mutation.
func withAuroraHealthCheck(node *AuroraHealthCheck) aurorahealthcheckOption {
	return func(m *AuroraHealthCheckMutation) {
		m.oldValue = func(context.Context) (*AuroraHealthCheck, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AuroraHealthCheckMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AuroraHealthCheckMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of AuroraHealthCheck entities.
func (m *AuroraHealthCheckMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AuroraHealthCheckMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AuroraHealthCheckMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().AuroraHealthCheck.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTs sets the "ts" field.
func (m *AuroraHealthCheckMutation) SetTs(t time.Time) {
	m.ts = &t
}

// Ts returns the value of the "ts" field in the mutation.
func (m *AuroraHealthCheckMutation) Ts() (r time.Time, exists bool) {
	v := m.ts
	if v == nil {
		return
	}
	return *v, true
}

// OldTs returns the old "ts" field's value of the AuroraHealthCheck entity.
// If the AuroraHealthCheck object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuroraHealthCheckMutation) OldTs(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTs is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTs requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTs: %w", err)
	}
	return oldValue.Ts, nil
}

// ResetTs resets all changes to the "ts" field.
func (m *AuroraHealthCheckMutation) ResetTs() {
	m.ts = nil
}

// Where appends a list predicates to the AuroraHealthCheckMutation builder.
func (m *AuroraHealthCheckMutation) Where(ps ...predicate.AuroraHealthCheck) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the AuroraHealthCheckMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *AuroraHealthCheckMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.AuroraHealthCheck, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *AuroraHealthCheckMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *AuroraHealthCheckMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (AuroraHealthCheck).
func (m *AuroraHealthCheckMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AuroraHealthCheckMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.ts != nil {
		fields = append(fields, aurorahealthcheck.FieldTs)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AuroraHealthCheckMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case aurorahealthcheck.FieldTs:
		return m.Ts()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AuroraHealthCheckMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case aurorahealthcheck.FieldTs:
		return m.OldTs(ctx)
	}
	return nil, fmt.Errorf("unknown AuroraHealthCheck field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AuroraHealthCheckMutation) SetField(name string, value ent.Value) error {
	switch name {
	case aurorahealthcheck.FieldTs:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTs(v)
		return nil
	}
	return fmt.Errorf("unknown AuroraHealthCheck field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AuroraHealthCheckMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AuroraHealthCheckMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AuroraHealthCheckMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown AuroraHealthCheck numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AuroraHealthCheckMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AuroraHealthCheckMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AuroraHealthCheckMutation) ClearField(name string) error {
	return fmt.Errorf("unknown AuroraHealthCheck nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AuroraHealthCheckMutation) ResetField(name string) error {
	switch name {
	case aurorahealthcheck.FieldTs:
		m.ResetTs()
		return nil
	}
	return fmt.Errorf("unknown AuroraHealthCheck field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AuroraHealthCheckMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AuroraHealthCheckMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AuroraHealthCheckMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AuroraHealthCheckMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AuroraHealthCheckMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AuroraHealthCheckMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AuroraHealthCheckMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown AuroraHealthCheck unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AuroraHealthCheckMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown AuroraHealthCheck edge %s", name)
}
