// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/kong/pg-aurora-client/internal/store/ent/aurorahealthcheck"
	"github.com/kong/pg-aurora-client/internal/store/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	aurorahealthcheckFields := schema.AuroraHealthCheck{}.Fields()
	_ = aurorahealthcheckFields
	// aurorahealthcheckDescTs is the schema descriptor for ts field.
	aurorahealthcheckDescTs := aurorahealthcheckFields[1].Descriptor()
	// aurorahealthcheck.DefaultTs holds the default value on creation for the ts field.
	aurorahealthcheck.DefaultTs = aurorahealthcheckDescTs.Default.(func() time.Time)
}
