{{- if .Values.aws.enabled }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.database.secret_name }}
spec:
  backendType: systemManager
  data:
    - key: /konnect.konghq.com/aurora/kadmin/failover-test
      name: POSTGRES_PASSWORD
  template:
    type: Opaque

{{ if .Values.database.tls.enabled }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  annotations: {}
  name: {{ .Values.external_secrets.database.caBundle.name }}
spec:
  backendType: secretsManager
  data:
    - key: {{ .Values.external_secrets.database.caBundle.storePath }}
      name: {{ .Values.external_secrets.database.caBundle.name }}
  template:
    type: Opaque
{{ end }}
{{- end }}