{{- if .Values.ingress.enabled }}
  {{- $fullName := include "pg-aurora-client.fullname" . }}
  {{- $fqdn :=  printf "%s.%s" .Values.subdomain .Values.domain }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "pg-aurora-client.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.ingress.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ printf "%s.%s" .Values.subdomain .Values.domain | quote }}
      secretName: {{ printf "%s-%s-tls" $fqdn $fullName | replace "." "-" | quote }}
  rules:
    - host: {{ $fqdn | quote }}
      http:
        paths:
          - path: /pg
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .Values.service.port }}
          - path: /pgx
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-pgx
                port:
                  number: {{ .Values.service.port }}
  {{- end }}