apiVersion: v1
kind: Service
metadata:
  name: {{ include "pg-aurora-client.fullname" . }}-pgx
  labels:
    {{- include "pg-aurora-client.base.labels" . | nindent 4 }}
    app.kubernetes.io/component: canary
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app.kubernetes.io/component: canary
