apiVersion: v1
kind: Service
metadata:
  name: {{ include "pg-aurora-client.fullname" . }}
  labels:
    {{- include "pg-aurora-client.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app.kubernetes.io/component: canary