apiVersion: v1
kind: Service
metadata:
  name: {{ include "pg-aurora-client.fullname" . }}
  labels:
    {{- include "pg-aurora-client.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    {{- include "pg-aurora-client.selectorLabels" . | nindent 4 }}