CREATE EXTENSION IF NOT EXISTS "hstore";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- create "aurora_health_check" table
CREATE TABLE "aurora_health_check"
(
    "id" bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ts" timestamptz NOT NULL,
    PRIMARY KEY ("id")
);


-- create "canary" table
CREATE TABLE "canary"
(
    "id" bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ts" timestamptz NOT NULL,
    PRIMARY KEY ("id")
);

INSERT INTO canary values(1, CURRENT_TIMESTAMP);
