// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuroraHealthCheck is the predicate function for aurorahealthcheck builders.
type AuroraHealthCheck func(*sql.Selector)
