CREATE USER koko WITH LOGIN PASSWORD 'koko';
GRANT USAGE ON SCHEMA public TO koko;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO koko;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO koko;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO koko;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO koko;

